### ISSUE TITLE
Error connecting to Brokers - We have tried it local, we have tried in EC2, We tried, we tried, but it would not do. 

### ISSUE THREAD

**Issue by chrisaddams** [jmaver-plume/kafkajs-msk-iam-authentication-mechanism#14]
We have tried it local, we have tried in EC2, We tried, we tried, but it would not do. 

Can you help? we tried exactly as specified, the only thing we changed where are broker addresses - hidden for securatae - and the region.
We ran the request 
```
BROKERS=b-1.ADDRESS.amazonaws.com, b-2.ADDRESS.amazonaws.com, b-3.ADDRESS.amazonaws.com REGION=OUR-REGION node . 
```
And got the response:
```
{"level":"ERROR","timestamp":"2022-08-18T13:15:06.054Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: getaddrinfo ENOTFOUND b-3.ADDRESS.amazonaws.com","retryCount":5,"retryTime":10902}
Error:  KafkaJSNonRetriableError
  Caused by: KafkaJSConnectionError: Connection error: getaddrinfo ENOTFOUND b-3.ADDRESS.amazonaws.com
    at TLSSocket.onError (/root/kafkajs-msk-iam-authentication-mechanism/example/simple/node_modules/kafkajs/src/network/connection.js:210:23)
    ... 3 lines matching cause stack trace ...
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  name: 'KafkaJSNumberOfRetriesExceeded',
  retriable: false,
  helpUrl: undefined,
  retryCount: 5,
  retryTime: 10902,
  [cause]: KafkaJSConnectionError: Connection error: getaddrinfo ENOTFOUND b-3.ADDRESS.amazonaws.com
      at TLSSocket.onError (/root/kafkajs-msk-iam-authentication-mechanism/example/simple/node_modules/kafkajs/src/network/connection.js:210:23)
      at TLSSocket.emit (node:events:513:28)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    retriable: true,
    helpUrl: undefined,
    broker: 'b-3.ADDRESS.amazonaws.com:9098',
    code: 'ENOTFOUND',
    [cause]: undefined
  }
}
```

**Comment by offsetcyan** [comment]
Do you have a port attached to these hostnames?
